name: Unit tests

on:
  pull_request:
    branches: [main]

jobs:
  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Update packages
      run: sudo apt-get update
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        python -m pip install -r requirements.txt

    - name: Test locally with unittest
      run: coverage run -m unittest tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
